# Generated by Django 5.1.3 on 2024-11-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cityOption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.TextField(blank=True, default='2024-11-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='join',
            field=models.CharField(blank=True, default=0.0008983111749910168, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
