# Generated by Django 5.0 on 2023-12-25 18:31

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tittle", models.CharField(max_length=255)),
                ("auteur", models.CharField(blank=True, max_length=255)),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                (
                    "text",
                    ckeditor.fields.RichTextField(blank=True, default=False, null=True),
                ),
                ("statut", models.TextField(blank=True, null=True)),
                ("is_featured", models.BooleanField(blank=True, null=True)),
                ("created_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BanqueImange",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("events", models.CharField(max_length=255)),
                ("comments", models.CharField(blank=True, max_length=255)),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                (
                    "is_featured",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("publie", models.BooleanField(blank=True, default=False, null=True)),
                ("statut", models.TextField(blank=True, null=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="image",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BanqueImangePhoto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("eventss", models.CharField(max_length=255)),
                ("commentss", models.CharField(blank=True, max_length=255)),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("publie", models.BooleanField(blank=True, default=False, null=True)),
                ("statut", models.TextField(blank=True, null=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="imageadd",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BanqueRessource",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("eventsss", models.CharField(max_length=255)),
                ("commentsss", models.CharField(blank=True, max_length=255)),
                ("photo", models.FileField(upload_to="photos/%Y/%m/%d/")),
                ("publie", models.BooleanField(blank=True, default=False, null=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="imageres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Demande",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("comments", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("adresse", models.CharField(max_length=255, null=True)),
                ("telephone", models.CharField(blank=True, max_length=255)),
                ("nbre", models.IntegerField(blank=True)),
                ("pearson", models.CharField(blank=True, max_length=255)),
                ("responsable", models.CharField(blank=True, max_length=255)),
                (
                    "is_featured",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("publie", models.BooleanField(blank=True, default=False, null=True)),
                ("statut", models.TextField(blank=True, null=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
