# Generated by Django 5.1.4 on 2025-01-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='link_intagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='link_tiktok',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='link_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
