# Generated by Django 5.1.4 on 2025-01-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_demande_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
