# Generated by Django 3.1.7 on 2021-08-06 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_auto_20210805_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanqueImangePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.CharField(max_length=255)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(blank=True, default=False, null=True)),
                ('publie', models.BooleanField(blank=True, default=False, null=True)),
                ('statut', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='imageadd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
