# Generated by Django 3.1.7 on 2021-08-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_banqueimangephoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banqueimangephoto',
            old_name='comments',
            new_name='commentss',
        ),
        migrations.RenameField(
            model_name='banqueimangephoto',
            old_name='events',
            new_name='eventss',
        ),
        migrations.RemoveField(
            model_name='banqueimangephoto',
            name='is_featured',
        ),
    ]
