# Generated by Django 5.0 on 2023-12-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_demande_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personne",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("fonction", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="demande",
            name="personnes",
            field=models.ManyToManyField(to="dashboard.personne"),
        ),
    ]
