# Generated by Django 5.1.4 on 2025-01-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_demande_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo1',
            field=models.FileField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='photo2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='photo3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='photo4',
            field=models.FileField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='photo5',
            field=models.FileField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
