# Generated by Django 3.1.7 on 2021-08-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210806_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banqueimangephoto',
            name='photo',
            field=models.FileField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
