# Generated by Django 3.1.7 on 2021-08-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210806_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banqueressource',
            old_name='commentss',
            new_name='commentsss',
        ),
        migrations.RenameField(
            model_name='banqueressource',
            old_name='eventss',
            new_name='eventsss',
        ),
    ]
