# Generated by Django 3.1.7 on 2021-08-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210806_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_featured',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
