# Generated by Django 4.1.2 on 2023-01-21 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profil_profile_remove_profil_user_profil_user'),
        ('dashboard', '0012_auto_20210806_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='profil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_demande', to='accounts.profil'),
        ),
    ]
