# Generated by Django 4.1.2 on 2023-01-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_demande_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='profil',
        ),
    ]
