# Generated by Django 3.1.7 on 2021-07-28 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('profession', models.CharField(blank=True, max_length=45, primary_key=True, serialize=False)),
                ('telephone', models.CharField(blank=True, max_length=45, null=True)),
                ('profile', models.CharField(blank=True, choices=[('developer', 'developer'), ('designer', 'designer'), ('photographe', 'photographe'), ('Manager', 'Manager'), ('redacteur', 'redacteur')], max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
