# Generated by Django 3.1.7 on 2021-07-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='profile',
            field=models.CharField(blank=True, choices=[('developer', 'developer'), ('designer', 'designer'), ('photographe', 'photographe'), ('Manager', 'Manager'), ('redacteur', 'redacteur'), ('groupecentrale', 'groupecentrale'), ('presse', 'presse')], max_length=255, null=True),
        ),
    ]
