# Generated by Django 4.1.2 on 2023-01-21 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210729_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.AddField(
            model_name='profil',
            name='user',
            field=models.ManyToManyField(null=True, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
    ]
