# Generated by Django 4.1.2 on 2023-01-21 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_remove_profil_user_profil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='profile',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('groupecentrale', 'groupecentrale'), ('presse', 'presse')], max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.AddField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
    ]
