# Generated by Django 5.1.4 on 2025-01-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type_organe',
            field=models.CharField(blank=True, choices=[('TFM', 'TFM'), ('SENEWEB', 'SENEWEB'), ('autre', 'autre')], max_length=255, null=True),
        ),
    ]
