# Generated by Django 5.1.4 on 2025-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_type_organe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_organe',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('groupecentrale', 'groupecentrale'), ('presse', 'presse'), ('freelancer', 'freelancer'), ('cscientifique', 'cscientifique'), ('digital', 'digital')], max_length=255, null=True),
        ),
    ]
