# Generated by Django 5.1.3 on 2024-11-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_field', models.CharField(default='SOME STRING', max_length=140)),
                ('image_field', models.ImageField(upload_to=None, verbose_name='')),
            ],
        ),
    ]
