# Generated by Django 3.1.7 on 2021-07-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlle_gallery', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(blank=True, default=False, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
